### For our analysis, weâ€™ve picked the FBI data.

Main FBI terms used in this dataset:

--> LEOKA: Law Enforcement Officers Killed and Assaulted

--> NIBRS: National Incident-Based Reporting System

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from pprint import pprint

# Import API key
import api_keys

In [2]:
proj_key = api_keys.fbi_key

base_url = "https://api.usa.gov/crime/fbi/sapi/api/participation/national?api_key=" + proj_key

req = requests.get(base_url).json()

#print(req)

In [3]:
#created list called fbi using req
fbi=list(req.values())

In [4]:
# created dictionary called fbi_data
fbi_data = {"data_year":[],
        "population":[],
        "total_agency_count" : [],
        "published_agency_count" : [],
        "active_agency_count" : [],
        "covered_agency_count" : [],
        "population_covered" : [],
        "agency_count_nibrs_submitting" : [],
        "agency_count_leoka_submitting" : [],
        "agency_count_pe_submitting" : [],
        "agency_count_srs_submitting" : [],
        "agency_count_asr_submitting" : [],
        "agency_count_hc_submitting" : [],
        "agency_count_supp_submitting" : [],
        "nibrs_population_covered" : [],
        "total_population" : []}

#using for loop appended values to fbi_data
for i in fbi[0]:
    fbi_data["data_year"].append(i['data_year'])
    fbi_data["population"].append(i['population'])
    fbi_data["total_agency_count"].append(i['total_agency_count'])
    fbi_data["published_agency_count"].append(i['published_agency_count'])
    fbi_data["active_agency_count"].append(i['active_agency_count'])
    fbi_data["covered_agency_count"].append(i['covered_agency_count'])
    fbi_data["population_covered"].append(i['population_covered'])
    fbi_data["agency_count_nibrs_submitting"].append(i['agency_count_nibrs_submitting'])
    fbi_data["agency_count_leoka_submitting"].append(i['agency_count_leoka_submitting'])
    fbi_data["agency_count_pe_submitting"].append(i['agency_count_pe_submitting'])
    fbi_data["agency_count_srs_submitting"].append(i['agency_count_srs_submitting'])
    fbi_data["agency_count_asr_submitting"].append(i['agency_count_asr_submitting'])
    fbi_data["agency_count_hc_submitting"].append(i['agency_count_hc_submitting'])
    fbi_data["agency_count_supp_submitting"].append(i['agency_count_supp_submitting'])
    fbi_data["nibrs_population_covered"].append(i['nibrs_population_covered'])
    fbi_data["total_population"].append(i['total_population'])

In [5]:
#created fbi_data_df dataframe using fbi_data dictionary
fbi_data_df = pd.DataFrame.from_dict(fbi_data)
fbi_data_df.head(5)

,data_year,population,total_agency_count,published_agency_count,active_agency_count,covered_agency_count,population_covered,agency_count_nibrs_submitting,agency_count_leoka_submitting,agency_count_pe_submitting,agency_count_srs_submitting,agency_count_asr_submitting,agency_count_hc_submitting,agency_count_supp_submitting,nibrs_population_covered,total_population
0,2019,337556149,18671,14993,22021,16,18660,8536,8356,15004,7786,11788,15520,15643,146950904,337556149
1,2018,336536616,18560,15236,21896,39,18737,7777,7122,15247,8200,13057,16107,15615,129148182,336536616
2,2017,335231625,18448,16393,21764,29,51097,7148,6680,16399,9381,13684,16285,15578,109218573,335231625
3,2016,329242793,18466,16921,21625,28,111631,7083,6388,16927,9986,13661,15940,15785,105287171,329242793
4,2015,327511036,18435,16813,21551,20,40665,6823,6223,16815,10102,13434,15096,15655,99789318,327511036

In [6]:
#using dtypes checked the data types for columns in fbi_data_df
fbi_data_df.dtypes

data_year                        int64
population                       int64
total_agency_count               int64
published_agency_count           int64
active_agency_count              int64
covered_agency_count             int64
population_covered               int64
agency_count_nibrs_submitting    int64
agency_count_leoka_submitting    int64
agency_count_pe_submitting       int64
agency_count_srs_submitting      int64
agency_count_asr_submitting      int64
agency_count_hc_submitting       int64
agency_count_supp_submitting     int64
nibrs_population_covered         int64
total_population                 int64
dtype: object

In [7]:
#created csv file called fbi_data from fbi_data_df
fbi_data_df.to_csv('fbi_data.csv')

In [8]:
#created popultation_df dataframe from fbi_data_df
population_df=fbi_data_df[["data_year", "population", "total_population"]]

#created csv file called population_data from population_df
population_df.to_csv('population_data.csv')

In [9]:
#created nibrs_df dataframe from fbi_data_df
nibrs_df=fbi_data_df[["data_year", "total_agency_count", "nibrs_population_covered", "agency_count_nibrs_submitting"]]

#created csv file called nibrs_data from nibrs_df
nibrs_df.to_csv('nibrs_data.csv')

In [10]:
#created leoka_df dataframe from fbi_data__df
leoka_df=fbi_data_df[["total_agency_count", "agency_count_leoka_submitting"]]

#created csv file called leoka_data from leoka_df
leoka_df.to_csv('leoka_data.csv')

In [34]:
# importing psycopg2 module after pip installing it in git bash
import psycopg2

#connection to Postgres by using the connect() method of the psycopg2 module
conn = psycopg2.connect("host=localhost dbname=FBI_Data user=postgres password=default")

In [27]:
#Cursor is created by the Connection object 
cur = conn.cursor()

#calling execute method on cursor object to create population table
cur.execute("""
    CREATE TABLE population(
    data_year integer PRIMARY KEY,
    population integer,
    total_population integer
   )
""")
conn.commit()

In [28]:
#importing csv module
import csv

#running INSERT query for each row to insert values into population table from population_data csv file. 
#and then commiting the transaction
with open('population_data.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    for row in reader:
        cur.execute(
        "INSERT INTO population(data_year, population, total_population) VALUES (%s, %s, %s)",
        row
    )
conn.commit()

In [29]:
#Cursor is created by the Connection object 
cur = conn.cursor()

#calling execute method on cursor object to create nibrs table
#and then commiting the transaction
cur.execute("""
    CREATE TABLE nibrs(
    data_year integer PRIMARY KEY,
    total_agency_count integer,
    nibrs_population_covered integer,
    agency_count_nibrs_submitting integer
   )
""")
conn.commit()

In [30]:
#importing csv module
import csv

#running INSERT query for each row to insert values into nibrs table from nibrs_data csv file. 
#and then commiting the transaction
with open('nibrs_data.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    for row in reader:
        cur.execute(
        "INSERT INTO nibrs(data_year,total_agency_count, nibrs_population_covered, agency_count_nibrs_submitting) VALUES (%s, %s, %s, %s)",
        row
    )
conn.commit()

In [35]:
#Cursor is created by the Connection object 
cur = conn.cursor()

#calling execute method on cursor object to create leoka table
#and then commiting the transaction
cur.execute("""
    CREATE TABLE leoka(
    total_agency_count integer PRIMARY KEY,
    agency_count_leoka_submitting integer
   )
""")
conn.commit()

In [36]:
#importing csv module
import csv

#running INSERT query for each row to insert values into leoka table from leoka_data csv file. 
#and then commiting the transaction
with open('leoka_data.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # Skip the header row.
    for row in reader:
        cur.execute(
        "INSERT INTO leoka(total_agency_count, agency_count_leoka_submitting) VALUES (%s, %s)",
        row
    )
conn.commit()